import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NextUiCustom } from "@/providers/NextUiCustom";
import { CustomNavbar } from "@/components/customNavbar/CustomNavbar";
import { Footer } from "@/components/footer/Footer";
// : ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
const poppin = Poppins({ subsets: ["devanagari"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Nitin Singh Negi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`${poppin.className}`}>
        <NextUiCustom>
          <CustomNavbar />
          {children}
          <Footer></Footer>
        </NextUiCustom>
      </body>
    </html>
  );
}
